package vectors

import (
	"crypto/ed25519"
	"encoding/hex"
	"encoding/json"

	"github.com/theapexlab/hackyeah2026/apps/prototype/go/protocol"
)

// skeletonSeed is the RFC 8032 test 1 secret key, the single key the walking skeleton trusts.
const skeletonSeed = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"

// SkeletonKey returns the skeleton's fixed test key pair.
func SkeletonKey() ed25519.PrivateKey {
	seed, err := hex.DecodeString(skeletonSeed)
	if err != nil {
		panic(err)
	}
	return ed25519.NewKeyFromSeed(seed)
}

// SkeletonRequest builds the vector for the reference request signed by the skeleton key.
func SkeletonRequest() (Vector, error) {
	key := SkeletonKey()
	msg := protocol.ReferenceRequest()
	tbs, err := protocol.SignedBytes(msg)
	if err != nil {
		return Vector{}, err
	}
	wire, err := protocol.Sign(protocol.Ed25519Key(key), msg)
	if err != nil {
		return Vector{}, err
	}
	return Vector{
		Name:   "skeleton-request-1",
		Source: "Generated by `go run ./go/cmd/vectors -update` from protocol.ReferenceRequest and the RFC 8032 test 1 key",
		Input: map[string]any{
			"secret_key_hex": skeletonSeed,
			"public_key_hex": hex.EncodeToString(key.Public().(ed25519.PublicKey)),
		},
		Intermediates: map[string]any{"signed_bytes_hex": hex.EncodeToString(tbs)},
		Output:        map[string]any{"request_hex": hex.EncodeToString(wire)},
		Expect:        "valid",
		Diagnostic:    "Signed request in deterministic CBOR; the signature covers the map with the signature element absent.",
	}, nil
}

// JSON renders the vector the way it is committed: indented, with a final newline.
func (v Vector) JSON() ([]byte, error) {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}
